# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"

resources:
  # input fastq for mapping reads of each sample
  fastq-data: "data/sample.fastq"

genome-properties:
  noise:
    treshold-seq-noise: 2
    treshold-cluster-size: 5
  # a diploid chromosome set is determined for this prototype,
  # for future use it can be configured here
  ploidy: 2
  mutationrates:
    substitution: 0.8999
    insertion: 0.05
    deletion: 0.05
  heterozygosity:
    substitution: 0.001
    insertion: 0.001
    deletion: 0.001

# optional graph figure outputs and additional xml files for subgraphs
graph-intermediate-steps:
  edit-distance-graph:
    # on activation please set a path to the variable graph_xml (rule noderad in noderad.smk),
    # on inactivation comment this variable out
    activate-xml: True
    # on activation please set a path to the variable graph_figure (rule noderad in noderad.smk),
    # on inactivation comment this variable out
    activate-figure: True
  connected-components:
    graph:
      # on activation please set a path to the variable connected_components_xml (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate-xml: True
      # on activation please set a path to the variable connected_components_figure (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate-figure: True
    subgraphs:
      # on activation please set a directory to the variable components_subgraphs (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate: True

params:
  # threshold for maximum distance value for building the graph, default: 23
  threshold_max_edit_distance: 12

