# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"

resources:
  # input fastq for mapping reads of each sample
  fastq-data: "data/sample.fastq"

genome-properties:
  noise:
    treshold-seq-noise: 2
    treshold-cluster-size: 5
  # a diploid chromosome set is determined for this prototype,
  # for future use it can be configured here
  ploidy: 2
  mutationrates:
    substitution: 0.8999
    insertion: 0.05
    deletion: 0.05
  heterozygosity:
    substitution: 0.001
    insertion: 0.001
    deletion: 0.001

# optional graph figure outputs and additional xml files for subgraphs
graph-intermediate-steps:
  edit-distance-graph:
    # on activation please set a path to the variable graph_xml (rule noderad in noderad.smk),
    # on inactivation comment this variable out
    activate-xml: True
    # on activation please set a path to the variable graph_figure (rule noderad in noderad.smk),
    # on inactivation comment this variable out
    activate-figure: True
  connected-components:
    graph:
      # on activation please set a path to the variable connected_components_xml (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate-xml: True
      # on activation please set a path to the variable connected_components_figure (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate-figure: True
    subgraphs:
      # on activation please set a directory to the variable components_subgraphs (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate: True

params:
  # threshold for maximum distance value for building the graph, default: 23
  threshold_max_edit_distance: 12
  # these cutadapt parameters need to contain the required flag(s) for
  # the type of adapter(s) to trim, i.e.:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  #   * `-a` for 3' adapter in the forward reads
  #   * `-g` for 5' adapter in the forward reads
  #   * `-b` for adapters anywhere in the forward reads
  # also, separate capitalised letter flags are required for adapters in
  # the reverse reads of paired end sequencing:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads
  cutadapt-se: "-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
   # reasoning behind parameters:
  #   * `-e 0.005`: the default cutadapt maximum error rate of `0.2` is far too high, for Illumina
  #     data the error rate is more in the range of `0.005` and setting it accordingly should avoid
  #     false positive adapter matches
  #   * `--minimum-overlap 7`: the cutadapt default minimum overlap of `5` did trimming on the level
  #     of expected adapter matches by chance
  cutadapt-pe: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -G AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  cutadapt-others: "-e 0.005 --overlap 7"
