# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

#samples: "config/samples_medium.tsv"

# minimal sets of samples for testing:
samples: "config/samples_small.tsv"
#samples: "config/samples_mini.tsv"
#samples: "config/samples_micro.tsv"

resources:
#  fastq-data: "data/medium_dataset/ddRAGEdataset_ATCACG_1.fastq"

# minimal datasets for testing:
  fastq-data: "data/small_dataset/ddRAGEdataset_GGCTAC_1.fastq"
#  fastq-data: "data/mini_dataset/ddRAGEdataset_GGCTAC_1.fastq"
#  fastq-data: "data/mini_dataset/reduced_ddRAGEdataset_GGCTAC_1.fastq"
#  fastq-data: "data/micro_dataset/ddRAGEdataset_ATCACG_1.fastq"

eval-data:
#  micro-dataset: "data/micro_dataset/ddRAGEdataset_GGCTAC_gt.yaml"
#  mini-dataset: "data/mini_dataset/ddRAGEdataset_GGCTAC_gt.yaml"
  small-dataset: "data/small_dataset/ddRAGEdataset_GGCTAC_gt.yaml"
#  medium-dataset: "data/medium_dataset/ddRAGEdataset_GGCTAC_gt.yaml"


genome-properties:
  noise:
    treshold-seq-noise:
        small-clusters: 2  # for clusters < treshold-cluster-size
        large-clusters: 4  # for clusters >= treshold-cluster-size
    treshold-cluster-size: 300
  # a diploid chromosome set is determined for this prototype,
  # for future use it can be configured here
  ploidy: 2
  errors-per-base:
    # sequencing errors in data from Illumina sequencing platforms as default values
    # source: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0976-y
    insertion: 2.8e-6
    deletion: 5.1e-6
  heterozygosity:
    substitution: 0.001
    insertion: 0.001
    deletion: 0.001

# optional graph figure outputs and additional xml files for subgraphs
graph-intermediate-steps:
  edit-distance-graph:
    # on activation please set a path to the variable graph_xml (rule noderad in noderad.smk),
    # on inactivation comment this variable out
    activate-xml: True
    # on activation please set a path to the variable graph_figure (rule noderad in noderad.smk),
    # on inactivation comment this variable out
    activate-figure: True
  connected-components:
    graph:
      # on activation please set a path to the variable connected_components_xml (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate-xml: True
      # on activation please set a path to the variable connected_components_figure (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate-figure: True
    subgraphs:
      # on activation please set a directory to the variable components_subgraphs (rule noderad in noderad.smk),
      # on inactivation comment this variable out
      activate: True

params:
  # threshold for maximum distance value for building the graph, default: 23
  threshold_max_edit_distance: 9
