name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: "--lint"

  Testing:
    runs-on: ubuntu-latest
#    needs:
#      - Linting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --conda-frontend mamba --show-failed-logs --cores 4 --conda-cleanup-pkgs cache --conda-frontend mamba"

    - name: Test report
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--report report.zip"
