name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v1.14.0
        with:
          directory: .test
          snakefile: Snakefile
          args: "--lint"

  Testing:
    runs-on: ubuntu-latest
#    needs:
#      - Linting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.14.0
      with:
        directory: .test
        snakefile: Snakefile
        args: "--use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache --conda-frontend mamba"

    - name: Test report
      uses: snakemake/snakemake-github-action@v1.14.0
      with:
        directory: .test
        snakefile: Snakefile
        args: "--report report.zip"
